refactor bfd startup script

diff --git a/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2 b/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
--- a/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
+++ b/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
@@ -1,4 +1,5 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -e -o pipefail # exit on any errors
 
 # The launcher picks up its config from environment variables, so set those.
 export BFD_PORT='{{ data_server_appserver_https_port }}'
@@ -7,8 +8,7 @@ export BFD_TRUSTSTORE='{{ data_server_dir }}/bluebutton-appserver-truststore.jks
 export BFD_WAR='{{ data_server_dir }}/{{ data_server_war | basename }}'
 export V2_ENABLED='{{ data_server_v2_enabled }}'
 
-# The WAR picks up its config from Java system properties, so set some variables we can use for
-# those.
+# The WAR picks up its config from Java system properties, so set variables we can use for those.
 LOGS_DIR='{{ data_server_dir }}/'
 DB_URL='{{ data_server_db_url }}'
 DB_USERNAME='{{ data_server_db_username }}'
@@ -20,7 +20,7 @@ BFD_V2_ENABLED='{{ data_server_v2_enabled }}'
 {% if data_server_new_relic_license_key is defined %}
 export NEW_RELIC_HOST='gov-collector.newrelic.com'
 export NEW_RELIC_LICENSE_KEY='{{ data_server_new_relic_license_key }}'
-export NEW_RELIC_LOG_FILE_PATH="${LOGS_DIR}"
+export NEW_RELIC_LOG_FILE_PATH="$LOGS_DIR"
 export NEW_RELIC_HIGH_SECURITY='false'
 export NEW_RELIC_EXTENSIONS_DIR='{{ data_server_dir }}/newrelic/extensions/'
 {% if data_server_proxy_host is defined %}
@@ -61,103 +61,131 @@ export NEW_RELIC_METRIC_PERIOD='{{ data_server_new_relic_metric_period }}'
 
 {% endif %}
 
-# Begin smoke testing startup routine
-STARTUP_TESTING_RETRIES='3'
-STARTUP_TESTING_BOOT_TIMEOUT='60'
-STARTUP_TESTING_REQ_TIMEOUT='15'
-STARTUP_TESTING_REQ_BACKOFF_TIMEOUT='10'
-STARTUP_TESTING_BENE_ID='-201'
+# startup/smoke test settings
+STARTUP_RETRIES='3'
+STARTUP_BOOT_TIMEOUT='60'
+STARTUP_REQ_TIMEOUT='15'
+STARTUP_REQ_BACKOFF_TIMEOUT='10'
+STARTUP_BENE_ID='-201'
+GRACEFUL_SHUTDOWN_TIMEOUT=30
+BFD_HOST="https://localhost:7443"
 
-##
-# Prints out the specified message.
-#
-# Params:
-# * $1: the message to log
-##
+
+# echo out log messages (appends date time stamp to message)
+# $1 == log message
 log() {
   echo "$(date +%F\ %T): $1"
 }
 
-##
-# Verifies that the specified endpoint/query can be queried via curl without error and produced the expected output.
-#
-# Params:
-# * $1: the full URL to query via curl
-# * $2: the value to confirm is present in the curl output; if not found, then the query should be regarded as unsuccessful
-##
-check_endpoint() {
-  set -o pipefail
-  curl --max-time $STARTUP_TESTING_REQ_TIMEOUT --silent --insecure --cert-type pem --cert "{{ data_server_dir }}/bluebutton-backend-test-data-server-client-test-keypair.pem" "$1" | grep "$2"
+# gracefully stops the bfd server if possible, else hard kills it
+stop_bfd_server(){
+  # if the server is running
+  if pgrep -F "{{ data_server_dir }}/bfd-server.pid" >/dev/null 2>&1; then
+    # try to gracefully stop the server (using sigint)
+    log "attempting to stop bfd server... "
+    pkill -INT -F "{{ data_server_dir }}/bfd-server.pid"
+    
+    # give it some time to stop
+    sleep $GRACEFUL_SHUTDOWN_TIMEOUT
+
+    # hard kill if it's still running
+    if pgrep -F "{{ data_server_dir }}/bfd-server.pid" >/dev/null 2>&1; then
+      pkill -9 -F "{{ data_server_dir }}/bfd-server.pid"
+    fi
+  else
+    log "bfd server not running"
+  fi
 }
 
-##
-# Runs test queries to verify that the server is working as expected. If not, issues a 'kill -INT' on the server's process to shut it down.
-##
-stop_service_if_failing() {
-  log "Waiting $STARTUP_TESTING_BOOT_TIMEOUT seconds for initial startup"
-  sleep $STARTUP_TESTING_BOOT_TIMEOUT
+# this function is called if anything goes wrong
+error_exit(){
+  log "BFD server failed to start properly, shutting down"
+  stop_bfd_server
+}
 
-  for I in $(seq $STARTUP_TESTING_RETRIES); do
-    log "Checking V1 metadata endpoint"
-    STARTUP_TESTING_CHECK_V1_METADATA=$(check_endpoint "https://localhost:7443/v1/fhir/metadata?_format=application%2Fjson%2Bfhir" "status")
-    STARTUP_TESTING_CHECK_V1_METADATA_EXIT=$?
+# handle trapped signals
+signal_exit() {
+  case $1 in
+    INT)
+      log "Startup halted by user" && stop_bfd_server ;;
+    *)
+      log "Received signal '$1'" && error_exit ;;
+  esac
+}
 
-    log "Checking V2 metadata endpoint"
-    STARTUP_TESTING_CHECK_V2_METADATA=$(check_endpoint "https://localhost:7443/v2/fhir/metadata?_format=application%2Fjson%2Bfhir" "status")
-    STARTUP_TESTING_CHECK_V2_METADATA_EXIT=$?
-
-    log "Checking V1 Coverage resource endpoint for bene $STARTUP_TESTING_BENE_ID"
-    STARTUP_TESTING_CHECK_V1_COVERAGE=$(check_endpoint "https://localhost:7443/v1/fhir/Coverage?beneficiary=$STARTUP_TESTING_BENE_ID&_format=application%2Fjson%2Bfhir" "id")
-    STARTUP_TESTING_CHECK_V1_COVERAGE_EXIT=$?
-
-    log "Checking V2 Coverage resource endpoint for bene $STARTUP_TESTING_BENE_ID"
-    STARTUP_TESTING_CHECK_V2_COVERAGE=$(check_endpoint "https://localhost:7443/v2/fhir/Coverage?beneficiary=$STARTUP_TESTING_BENE_ID&_format=application%2Fjson%2Bfhir" "id")
-    STARTUP_TESTING_CHECK_V2_COVERAGE_EXIT=$?
-
-    log "Checking V1 EOB resource endpoint for bene $STARTUP_TESTING_BENE_ID"
-    STARTUP_TESTING_CHECK_V1_EOB=$(check_endpoint "https://localhost:7443/v1/fhir/ExplanationOfBenefit/?_format=application%2Ffhir%2Bjson&patient=$STARTUP_TESTING_BENE_ID" "id")
-    STARTUP_TESTING_CHECK_V1_EOB_EXIT=$?
-
-    log "Checking V2 EOB resource endpoint for bene $STARTUP_TESTING_BENE_ID"
-    STARTUP_TESTING_CHECK_V2_EOB=$(check_endpoint "https://localhost:7443/v2/fhir/ExplanationOfBenefit/?_format=application%2Ffhir%2Bjson&patient=$STARTUP_TESTING_BENE_ID" "id")
-    STARTUP_TESTING_CHECK_V2_EOB_EXIT=$?
-
-    if [[ $STARTUP_TESTING_CHECK_V1_METADATA_EXIT == 0 ]] && [[ $STARTUP_TESTING_CHECK_V1_COVERAGE_EXIT == 0 ]] && [[ $STARTUP_TESTING_CHECK_V1_EOB_EXIT == 0 ]] && [[ $STARTUP_TESTING_CHECK_V2_METADATA_EXIT == 0 ]] && [[ $STARTUP_TESTING_CHECK_V2_COVERAGE_EXIT == 0 ]] && [[ $STARTUP_TESTING_CHECK_V2_EOB_EXIT == 0 ]]; then
-      log "Server started properly"
-      return 0
-    elif [[ $I -lt $STARTUP_TESTING_RETRIES ]]; then
-      log "Server failed to start properly, backing off"
-      sleep $STARTUP_TESTING_REQ_BACKOFF_TIMEOUT
+# checks that the specified endpoint/query can be queried via curl without error and produced the expected output
+# $1 == the name of the endpoint
+# $2 == endpoint URI
+# $3 == the value to confirm is present in the curl output; if not found, then the query should be regarded as unsuccessful
+curl_options="--silent --insecure "
+curl_options+="--max-time $STARTUP_REQ_TIMEOUT "
+curl_options+="--cert-type pem --cert {{ data_server_dir }}/bluebutton-backend-test-data-server-client-test-keypair.pem"
+check_endpoint() {
+  log "Checking $1 endpoint.."
+  for i in ${1..$STARTUP_RETRIES}; do
+    if grep "$3" <( curl "$curl_options" "${BFD_HOST}/${2}" ); then
+      log "$1 check passed"
+      return
+    else
+      log "$1 check failed (attempt $i)"
+      sleep $STARTUP_REQ_BACKOFF_TIMEOUT
     fi
   done
-
-  log "Server failed to start properly, shutting down"
-  STARTUP_TESTING_BFD_PID=$(ps -ef | grep 'DataServerLauncherApp' | grep -v grep | awk '{print $2}')
-  STARTUP_TESTING_BFD_PID_EXIT=$?
-
-  if [[ $STARTUP_TESTING_BFD_PID_EXIT == 0 ]] && kill -INT $STARTUP_TESTING_BFD_PID; then
-    log "Server shut down gracefully"
-  else
-    log "Error shutting down server gracefully"
-  fi
-  return 1
+  log "All $1 tests failed. Giving up."
+  exit 1
 }
 
-(stop_service_if_failing >>"{{ data_server_dir }}/bfd-server-startup.log" 2>&1) &
-# End smoke testing startup routine
+# runs smoke tests to verify that the server is working as expected
+run_smoke_tests() {
+  local OK=false
+  while [ $STARTUP_BOOT_TIMEOUT -gt 0 ]; do
+    if check_endpoint "${BFD_HOST}/v1/fhir/metadata?_format=application%2Fjson%2Bfhir" "status" >/dev/null 2>&1; then
+      OK=true
+      break
+    else
+      sleep 1
+    fi
+    STARTUP_BOOT_TIMEOUT=$STARTUP_BOOT_TIMEOUT-1
+  done
 
-# Set some additional variables.
-JVM_ARGS='{{ data_server_appserver_jvmargs }}'
+  if ! $OK; then
+    log "Failed to startup API after $STARTUP_BOOT_TIMEOUT seconds. Giving up."
+    exit 1
+  fi
+
+  # api is up.. run endpoint checks
+  check_endpoint 'v1 metadata' 'v1/fhir/metadata?_format=application%2Fjson%2Bfhir' 'status' || error_exit
+  check_endpoint 'v2 metadata' 'v2/fhir/metadata?_format=application%2Fjson%2Bfhir' 'status' || error_exit
+
+  check_endpoint 'v1 coverage' "v1/fhir/Coverage?beneficiary=${STARTUP_BENE_ID}&_format=application%2Fjson%2Bfhir" 'id' || error_exit
+  check_endpoint 'v2 coverage' "v2/fhir/Coverage?beneficiary=${STARTUP_BENE_ID}&_format=application%2Fjson%2Bfhir" 'id' || error_exit
+  
+  check_endpoint 'v1 eob' "v1/fhir/ExplanationOfBenefit/?_format=application%2Ffhir%2Bjson&patient=${STARTUP_BENE_ID}" 'id' || error_exit
+  check_endpoint 'v2 eob' "v2/fhir/ExplanationOfBenefit/?_format=application%2Ffhir%2Bjson&patient=${STARTUP_BENE_ID}" 'id' || error_exit
+}
+
+# handle signals
+trap "signal_exit TERM" TERM HUP
+trap "signal_exit INT"  INT
+
+# run the smoke tests in the background
+(run_smoke_tests >>"{{ data_server_dir }}/bfd-server-startup.log" 2>&1) &
+
+# java args
+JVM_ARGS='javaagent:{{ data_server_dir }}/newrelic/newrelic.jar '
+JVM_ARGS+='{{ data_server_appserver_jvmargs }} '
+JVM_ARGS+="-DbfdServer.logs.dir='${LOGS_DIR}' "
+JVM_ARGS+="-DbfdServer.db.url='${DB_URL}' "
+JVM_ARGS+="-DbfdServer.db.username='${DB_USERNAME}' "
+JVM_ARGS+="-DbfdServer.db.password='${DB_PASSWORD}' "
+JVM_ARGS+="-DbfdServer.db.connections.max=${DB_CONNECTIONS_MAX} "
+JVM_ARGS+="-DbfdServer.v2.enabled=${BFD_V2_ENABLED} "
+JVM_ARGS+='-jar "{{ data_server_dir }}/{{ data_server_launcher | basename }}" '
 
 # 3... 2... 1... launch!
-java \
-  -javaagent:{{ data_server_dir }}/newrelic/newrelic.jar \
-  ${JVM_ARGS} \
-  "-DbfdServer.logs.dir=${LOGS_DIR}" \
-  "-DbfdServer.db.url=${DB_URL}" \
-  "-DbfdServer.db.username=${DB_USERNAME}" \
-  "-DbfdServer.db.password=${DB_PASSWORD}" \
-  "-DbfdServer.db.connections.max=${DB_CONNECTIONS_MAX}" \
-  "-DbfdServer.v2.enabled=${BFD_V2_ENABLED}" \
-  -jar "{{ data_server_dir }}/{{ data_server_launcher | basename }}" \
-  >>"{{ data_server_dir }}/bluebutton-server-app-log.json" 2>&1
+if java "$JVM_ARGS" >>"{{ data_server_dir }}/bluebutton-server-app-log.json" 2>&1; then
+  # store the pid
+  echo $! >"{{ data_server_dir }}/bfd-server.pid"
+else
+  error_exit
+fi
